version: '3.7'

services:
  survey:
    container_name: survey
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3001
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}